import type { CalendarEvent, InboxMessage, Listing, Venue } from "@/lib/types";

const HOUR = 3_600_000;

export const seedListings: Listing[] = [
  {
    id: "scrim-1",
    createdAt: Date.now() - HOUR * 4,
    teamName: "Irvine Strikers FC",
    gender: "Boys",
    age: "U14",
    level: "Club",
    subLevel: "Premier (ECNL / RL)",
    travelRadius: "Up to 25 miles",
    date: "2026-08-22",
    time: "Morning",
    location: "Irvine Great Park Field 3, Irvine CA",
    isHosting: true,
    hasRef: true,
    refFee: "50/50 Split",
    hasFieldFee: false,
    notes: "Looking for a competitive 11v11 warmup match before the fall tournament.",
    status: "open",
  },
  {
    id: "scrim-2",
    createdAt: Date.now() - HOUR * 18,
    teamName: "Mission Viejo HS Varsity",
    gender: "Girls",
    age: "Varsity",
    level: "High School",
    subLevel: "CIF Division 2",
    travelRadius: "Up to 50 miles",
    date: "2026-08-29",
    time: "Afternoon",
    location: "Mission Viejo High School Main Pitch",
    isHosting: true,
    hasRef: true,
    refFee: "Host Pays Ref",
    hasFieldFee: false,
    notes: "Pre-season friendly. Paid official assigned.",
    status: "open",
  },
  {
    id: "scrim-3",
    createdAt: Date.now() - HOUR * 30,
    teamName: "South County AYSO Select",
    gender: "Boys",
    age: "U12",
    level: "Rec",
    subLevel: "AYSO Extra",
    travelRadius: "Up to 10 miles",
    date: "2026-08-25",
    time: "Evening",
    location: "Laguna Niguel Regional Park",
    isHosting: false,
    hasRef: false,
    refFee: "Visitor Pays",
    hasFieldFee: true,
    notes: "Willing to travel locally for a 9v9 game.",
    status: "open",
  },
  {
    id: "scrim-4",
    createdAt: Date.now() - HOUR * 40,
    teamName: "Tustin Blues U16 Girls",
    gender: "Girls",
    age: "U16",
    level: "Club",
    subLevel: "Elite (MLS Next / GA)",
    travelRadius: "Up to 50 miles",
    date: "2026-09-05",
    time: "Morning",
    location: "Tustin Sports Park Field 2",
    isHosting: true,
    hasRef: true,
    refFee: "50/50 Split",
    hasFieldFee: false,
    notes: "Need a fast, physical opponent to prep for playoffs.",
    status: "open",
  },
];

export const seedVenues: Venue[] = [
  { id: "v-1", name: "Irvine Great Park Sports Complex", city: "Irvine, CA", fields: "12 Turf Pitches", lights: true, parking: "Free Lot A/B" },
  { id: "v-2", name: "Orange County Great Park Soccer Stadium", city: "Irvine, CA", fields: "Stadium Grass Pitch", lights: true, parking: "VIP Lot" },
  { id: "v-3", name: "Laguna Niguel Regional Park", city: "Laguna Niguel, CA", fields: "4 Grass Pitches", lights: false, parking: "Paid Park Entrance" },
  { id: "v-4", name: "Tustin Sports Park", city: "Tustin, CA", fields: "6 Turf Pitches", lights: true, parking: "Free Lot" },
];

export const seedInbox: InboxMessage[] = [
  {
    id: "msg-101",
    senderTeamName: "Saddleback United U14",
    subject: "Interest in Irvine Strikers Friendly",
    body: "Hey Coach! We saw your listing for Aug 22 morning at Great Park. We're available and can split ref fees. Let us know if you want to lock it in!",
    timestamp: Date.now() - HOUR * 2,
    isRead: false,
    listingId: "scrim-1",
  },
];

export const seedCalendarEvents: CalendarEvent[] = [
  {
    id: "cal-1",
    title: "League Fixture vs. Capistrano Valley",
    date: "2026-08-22",
    time: "Morning",
    location: "Home Pitch",
    kind: "league",
  },
  {
    id: "cal-2",
    title: "Fields closed for city maintenance",
    date: "2026-08-29",
    time: "Afternoon",
    kind: "blackout",
  },
];
